# Use an official Apache Airflow runtime as a parent image
FROM apache/airflow:2.7.3-python3.11

# Install Virtual Environment
RUN pip install --upgrade pip && \
    pip install apache-airflow[virtualenv]==2.7.3



