name: image-build-and-publish

# This workflow builds and publishes container images.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container:
          - name: risingwave_udf_median
            tag: 0.0.13
          - name: risingwave_udf_chisquared
            tag: 0.0.10
          # - name: jupyterhub
          #   tag: 0.3.28
          # - name: pulsar
          #   tag: 0.311.5
          # - name: superset
          #   tag: 0.301.6
          # - name: trino
          #   tag: 0.2.368
          # - name: hive_metastore
          #   tag: 0.0.19
          # - name: pulsar_dag
          #   tag: 0.0.1
          # - name: airflow
          #   tag: 0.4.273
          # - name: postgresql
          #   tag: 0.155.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.container.name }} image
        uses: docker/build-push-action@v5
        with:
          context: ./container/${{ matrix.container.name }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.container.name }}:${{ matrix.container.tag }}
